dist: trusty
sudo: false

language: node_js
node_js:
 - "8.11"

branches:
  only:
    - master

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

script:
  - npm run test -- --no-watch --no-progress
  - ng build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/restaurants
  on:
